refactor: improvements to various functions

diff --git a/add b/add
--- a/add
+++ b/add
@@ -21,7 +21,7 @@ usage() {
     echo "Usage: $NAME [wsl|pi|kali] [packages...]"
 }
 
-parge_args() {
+parse_args() {
     if (($# == 0)); then
         usage >&2
         exit 1
@@ -61,23 +61,24 @@ verify_packages() {
             query=(pacman -Si)
         fi
     else
-        query=(apt show)
+        query=(ssh "$MACHINE" apt show)
     fi
 
     for package in "${PACKAGES[@]}"; do
-        if ! ssh "$MACHINE" "${query[@]}" "$package" &>/dev/null; then
+        if "${query[@]}" "$package" &>/dev/null; then
+            VALID_PACKAGES+=("$package")
+        else
             INVALID_PACKAGES+=("$package")
-            continue
         fi
-        VALID_PACKAGES+=("$package")
     done
 }
 
-invalid_packages() {
-    echo "Invalid packages: $(
-        joined=$(printf ', %s' "${INVALID_PACKAGES[@]}")
-        echo "${joined:2}"
-    )" >&2
+print_invalid_packages() {
+    echo >&2
+    echo "The following packages were not added" >&2
+    local joined
+    joined=$(printf ', %s' "${INVALID_PACKAGES[@]}")
+    echo "Invalid packages: ${joined:2}" >&2
 }
 
 packages_path() {
@@ -93,13 +94,7 @@ packages_path() {
 }
 
 add_packages() {
-    local name path package
-
-    if [[ "$MACHINE" == "wsl" ]]; then
-        name="yay"
-    else
-        name="apt"
-    fi
+    local path package
 
     path=$(packages_path)
 
@@ -122,12 +117,14 @@ sync_packages() {
 }
 
 main() {
-    if [[ "$HOST" != "wsl" ]]; then
+    if [[ "$HOSTNAME" != "wsl" ]]; then
         echo "This script should only be run on wsl" >&2
         exit 1
     fi
 
-    parge_args "$@"
+    local joined
+
+    parse_args "$@"
 
     [[ $MACHINE != "wsl" ]] && check_connection
 
@@ -135,9 +132,7 @@ main() {
 
     if ((${#VALID_PACKAGES[@]} == 0)); then
         echo "No valid packages were provided" >&2
-        echo
-        echo "The following packages were not added"
-        invalid_packages
+        print_invalid_packages
         exit 1
     fi
 
@@ -145,15 +140,11 @@ main() {
     sync_packages
 
     echo "The following packages were added"
-    echo "Added packages: $(
-        joined=$(printf ', %s' "${VALID_PACKAGES[@]}")
-        echo "${joined:2}"
-    )"
+    joined=$(printf ', %s' "${VALID_PACKAGES[@]}")
+    echo "Added packages: ${joined:2}"
 
     if ((${#INVALID_PACKAGES[@]} > 0)); then
-        echo
-        echo "The following packages were not added"
-        invalid_packages
+        print_invalid_packages
         exit 1
     fi
 }
